language: android

sudo: false

jdk: oraclejdk8

dist : trusty

android:
  components:
    - tools
    - platform-tools
    - android-29
    - build-tools-29.0.2
   
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "${TRAVIS_BUILD_DIR}/gradle/caches/"
  - "${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

script:
  - ./gradlew build --stacktrace

after_success:
  - bash scripts/prep-key.sh
  - bash scripts/upload-apk.sh

